/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZebrasRouteImport } from './routes/zebras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartidaIdRouteImport } from './routes/partida.$id'

const ZebrasRoute = ZebrasRouteImport.update({
  id: '/zebras',
  path: '/zebras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaIdRoute = PartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zebras': typeof ZebrasRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zebras': typeof ZebrasRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/zebras': typeof ZebrasRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zebras' | '/partida/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zebras' | '/partida/$id'
  id: '__root__' | '/' | '/zebras' | '/partida/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZebrasRoute: typeof ZebrasRoute
  PartidaIdRoute: typeof PartidaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zebras': {
      id: '/zebras'
      path: '/zebras'
      fullPath: '/zebras'
      preLoaderRoute: typeof ZebrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$id': {
      id: '/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof PartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZebrasRoute: ZebrasRoute,
  PartidaIdRoute: PartidaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
